declare module "redux-persist/integration/react"
declare module "@rootstrap/redux-tools"
declare module "@rootstrap/validate"
declare module "react-native-multiple-select-list"
declare module "react-native-select-two"