name: lint
on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - main
      - master
      - staging
      - development

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # This needs to match Node version in package.json
      - uses: actions/setup-node@v1
        with:
          node-version: '^14.5.0'

      - name: Install Dependencies
        run: yarn

      - uses: ././github/workflows/lint.yml

      - name: Run Prettier
        run: yarn run prettier